<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introductie-Python" data-toc-modified-id="Introductie-Python-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introductie Python</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Inhoud-van-de-introductie" data-toc-modified-id="Inhoud-van-de-introductie-1.0.1"><span class="toc-item-num">1.0.1&nbsp;&nbsp;</span>Inhoud van de introductie</a></span></li></ul></li><li><span><a href="#Rekenen-met-python" data-toc-modified-id="Rekenen-met-python-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Rekenen met python</a></span><ul class="toc-item"><li><span><a href="#Nu-jij" data-toc-modified-id="Nu-jij-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Nu jij</a></span></li></ul></li><li><span><a href="#Rekenen-met-woorden" data-toc-modified-id="Rekenen-met-woorden-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Rekenen met woorden</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Probeer-het-uit-en-vergeet-het-nooit-meer." data-toc-modified-id="Probeer-het-uit-en-vergeet-het-nooit-meer.-1.2.0.1"><span class="toc-item-num">1.2.0.1&nbsp;&nbsp;</span>Probeer het uit en vergeet het nooit meer.</a></span></li></ul></li></ul></li><li><span><a href="#Type-casting" data-toc-modified-id="Type-casting-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Type casting</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Experimenteer-met-de-volgende-code" data-toc-modified-id="Experimenteer-met-de-volgende-code-1.3.0.1"><span class="toc-item-num">1.3.0.1&nbsp;&nbsp;</span>Experimenteer met de volgende code</a></span></li></ul></li><li><span><a href="#De-mooie-vermenigvuldiging:-loops" data-toc-modified-id="De-mooie-vermenigvuldiging:-loops-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>De mooie vermenigvuldiging: loops</a></span><ul class="toc-item"><li><span><a href="#range()-en-lijsten" data-toc-modified-id="range()-en-lijsten-1.3.1.1"><span class="toc-item-num">1.3.1.1&nbsp;&nbsp;</span><code>range()</code> en lijsten</a></span></li></ul></li><li><span><a href="#Onze-mooie-vermenigvuldiging" data-toc-modified-id="Onze-mooie-vermenigvuldiging-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>Onze mooie vermenigvuldiging</a></span></li></ul></li><li><span><a href="#Nu-JIJ:" data-toc-modified-id="Nu-JIJ:-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Nu JIJ:</a></span></li><li><span><a href="#Antwoorden" data-toc-modified-id="Antwoorden-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Antwoorden</a></span><ul class="toc-item"><li><span><a href="#Print-nog-meer-van-dit-soort-producten.-Kan-je-verklaren-wat-er-gebeurt?" data-toc-modified-id="Print-nog-meer-van-dit-soort-producten.-Kan-je-verklaren-wat-er-gebeurt?-1.5.1"><span class="toc-item-num">1.5.1&nbsp;&nbsp;</span>Print nog meer van dit soort producten. Kan je verklaren wat er gebeurt?</a></span></li><li><span><a href="#Probeer-ze-eens-in-de-omgekeerde-volgorde-uit-te-printen." data-toc-modified-id="Probeer-ze-eens-in-de-omgekeerde-volgorde-uit-te-printen.-1.5.2"><span class="toc-item-num">1.5.2&nbsp;&nbsp;</span>Probeer ze eens in de omgekeerde volgorde uit te printen.</a></span></li><li><span><a href="#Kan-je-ze-zo-uit-printen-dat-de-uitkomst-een-mooie-driehoek-wordt?" data-toc-modified-id="Kan-je-ze-zo-uit-printen-dat-de-uitkomst-een-mooie-driehoek-wordt?-1.5.3"><span class="toc-item-num">1.5.3&nbsp;&nbsp;</span>Kan je ze zo uit printen dat de uitkomst een mooie driehoek wordt?</a></span></li></ul></li><li><span><a href="#Maak-een-functie-voor-dit-soort-driehoeksrijtjes-met-als-argumenten-het-getal-waarmee-je-begint-(1,2,3,..)-en-het-aantal-keer-dat-je-het-product-uitvoert." data-toc-modified-id="Maak-een-functie-voor-dit-soort-driehoeksrijtjes-met-als-argumenten-het-getal-waarmee-je-begint-(1,2,3,..)-en-het-aantal-keer-dat-je-het-product-uitvoert.-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Maak een functie voor dit soort driehoeksrijtjes met als argumenten het getal waarmee je begint (1,2,3,..) en het aantal keer dat je het product uitvoert.</a></span><ul class="toc-item"><li><span><a href="#Speciale-Kerst-Boom" data-toc-modified-id="Speciale-Kerst-Boom-1.6.1"><span class="toc-item-num">1.6.1&nbsp;&nbsp;</span>Speciale Kerst Boom</a></span></li></ul></li><li><span><a href="#Python-kan-alles!" data-toc-modified-id="Python-kan-alles!-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Python kan alles!</a></span><ul class="toc-item"><li><span><a href="#Hierna" data-toc-modified-id="Hierna-1.7.1"><span class="toc-item-num">1.7.1&nbsp;&nbsp;</span>Hierna</a></span></li></ul></li><li><span><a href="#Fibonacci" data-toc-modified-id="Fibonacci-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Fibonacci</a></span><ul class="toc-item"><li><span><a href="#Voortplanting-van-konijnen" data-toc-modified-id="Voortplanting-van-konijnen-1.8.1"><span class="toc-item-num">1.8.1&nbsp;&nbsp;</span>Voortplanting van konijnen</a></span></li></ul></li></ul></li><li><span><a href="#In-formele-regels" data-toc-modified-id="In-formele-regels-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>In formele regels</a></span></li><li><span><a href="#Fibonacci-reeks-in-de-Nautilus-schelp" data-toc-modified-id="Fibonacci-reeks-in-de-Nautilus-schelp-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Fibonacci reeks in de Nautilus schelp</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Programmeren" data-toc-modified-id="Programmeren-3.0.1"><span class="toc-item-num">3.0.1&nbsp;&nbsp;</span>Programmeren</a></span><ul class="toc-item"><li><span><a href="#In-Python" data-toc-modified-id="In-Python-3.0.1.1"><span class="toc-item-num">3.0.1.1&nbsp;&nbsp;</span>In Python</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Nu-met-echte-konijnen" data-toc-modified-id="Nu-met-echte-konijnen-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Nu met echte konijnen</a></span></li><li><span><a href="#Tot-slot:-mail-sturen-vanuit-Python!" data-toc-modified-id="Tot-slot:-mail-sturen-vanuit-Python!-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Tot slot: mail sturen vanuit Python!</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Be-aware" data-toc-modified-id="Be-aware-5.0.1"><span class="toc-item-num">5.0.1&nbsp;&nbsp;</span>Be aware</a></span></li></ul></li></ul></li><li><span><a href="#Mail-versturen,-spammen" data-toc-modified-id="Mail-versturen,-spammen-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Mail versturen, spammen</a></span></li></ul></div>

In [1]:
from numpy import arange as range

range(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Introductie Python

* We introduceren Python met een grappige _rekenvondst_: 
    * als je $1\ldots 1$ met zichzelf vermenigvuldigt krijg je $123\ldots 321$

```
         1 x 1         =         1
        11 x 11        =        121
       111 x 111       =       12321
      1111 x 1111      =      1234321
     11111 x 11111     =     123454321
    111111 x 111111    =    12345654321
   1111111 x 1111111   =   1234567654321
  11111111 x 11111111  =  123456787654321
 111111111 x 111111111 = 12345678987654321 ```

### Inhoud van de introductie
1. Python is een rekenmachine
2. Je kunt ook 'rekenen' met woorden
3. Type-casting: omzetten van het ene naar het andere type
4. loops

## Rekenen met python

In [2]:
1*1

1

In [3]:
11*11

121

In [4]:
111*111

12321

### Nu jij

1. Ga optellen (ja met `+`)
1. Ga machtsverheffen: $2^3$, 2 tot de macht 3
    * is gelijk aan $2 \times 2\times 2$
    * In python: `2**3`
1. Ga aftrekken
1. Ga delen.
    * hier gebeurt iets geks
    * wat is hier aan de hand?

In [5]:
# ga hier lekker proberen
# als je iets wilt uitrekenen, doe je Shift Return (of je drukt op de play knop boven in het menu)

2**4==2**3 *2

True

## Rekenen met woorden

* Woorden (_strings_) in Python staan altijd tussen quotes (enkele of dubbele)
* Wat denk je dat `'bla'+'bla'` betekent?
* En `'bla'* 3`
* en `'bla'*'bla'`

#### Probeer het uit en vergeet het nooit meer.

In [6]:
'bla'+'bla'

'blabla'

In [7]:
'bla'* 1000

'blablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablabla

In [8]:
'bla'*'bla'

TypeError: can't multiply sequence by non-int of type 'str'

## Type casting

* Elk object heeft een type
* Vaak is dit _impliciet_: Python probeert te raden wat het type is.
* Python is slim: het kan het _woord_ `'98'` omzetten in het _getal_ `98`.
* Zie je het verschil?

#### Experimenteer met de volgende code
* Maak zelf andere voorbeelden
* Doe lekker gek

In [9]:
int('5')* 5

25

In [10]:
str(5)*5

'55555'

In [11]:
type(5)

int

In [12]:
type('5')

str

In [13]:
henkie89='5'


In [14]:
henkie89.#TAB

SyntaxError: invalid syntax (<ipython-input-14-565ed618d3b1>, line 1)

In [ ]:
zes_getal=6
zes_getal?

### De mooie vermenigvuldiging: loops

* We gaan alle producten $x\times x$, voor $x$ een rijtje van 1 tot 9 enen, laten uitvoeren.
* We doen dit met een _for loop_
* we gebruiken
    * `range`
    * vermenigvuldigen van een "de letter" 1
    * type casting
    

#### `range()` en lijsten
* Python telt niet vanaf 1 maar vanaf 0
* een lijst is een rijtje objecten, aangegeven met vierkante haken

In [15]:
# for Python 3 
from numpy import arange as range

range(3)

array([0, 1, 2])

In [16]:
range(1,5)

array([1, 2, 3, 4])

### Onze mooie vermenigvuldiging

In [17]:
for i in range(1,10): 
    eentjes= int('1'*i)
    print(i,  eentjes,  eentjes*eentjes)

1 1 1
2 11 121
3 111 12321
4 1111 1234321
5 11111 123454321
6 111111 12345654321
7 1111111 1234567654321
8 11111111 123456787654321
9 111111111 12345678987654321


## Nu JIJ:
1. Print nog meer van dit soort producten. Kan je verklaren wat er gebeurt?
1. Probeer ze eens in de omgekeerde volgorde uit te printen.
1. Kan je ze zo uit printen dat de uitkomst een mooie driehoek wordt?
1. Maak een functie voor dit soort driehoeksrijtjes met als argumenten het getal waarmee je begint (1,2,3,..) en het aantal keer dat je het product uitvoert.

In [18]:
# Ga hier aan de slag
# Doe niet flauw en kijk niet naar de antwoorden beneden.


## Antwoorden

### Print nog meer van dit soort producten. Kan je verklaren wat er gebeurt?

In [19]:
# Print nog meer van dit soort producten. Kan je verklaren wat er gebeurt?
for i in range(1,10): 
    print(int('2'*i)**2)

4
484
49284
4937284
493817284
49382617284
4938270617284
493827150617284
49382715950617284


### Probeer ze eens in de omgekeerde volgorde uit te printen.

In [20]:
# Probeer ze eens in de omgekeerde volgorde uit te printen.
for i in range(1,10): 
     print(int('2'*(10-i))**2)

49382715950617284
493827150617284
4938270617284
49382617284
493817284
4937284
49284
484
4


In [21]:
range?

In [22]:
range(9,0,-1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [23]:
range(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
# Probeer ze eens in de omgekeerde volgorde uit te printen.
for i in range(9,0,-1): 
     print(int('2'* i)**2)

49382715950617284
493827150617284
4938270617284
49382617284
493817284
4937284
49284
484
4


### Kan je ze zo uit printen dat de uitkomst een mooie driehoek wordt?

In [25]:
#Kan je ze zo uit printen dat de uitkomst een mooie driehoek wordt?
for i in range(1,10):  
        uitkomst = int('1'*i) * int('1'*i)
        extra = 10-i 
        print(extra*' '+ str(uitkomst)+extra*' '+'heerlijk')
                   

         1         heerlijk
        121        heerlijk
       12321       heerlijk
      1234321      heerlijk
     123454321     heerlijk
    12345654321    heerlijk
   1234567654321   heerlijk
  123456787654321  heerlijk
 12345678987654321 heerlijk


## Maak een functie voor dit soort driehoeksrijtjes met als argumenten het getal waarmee je begint (1,2,3,..) en het aantal keer dat je het product uitvoert.

In [26]:
def getallenboom(getal,aantal):
    for i in range(1,aantal):  
        uitkomst = int(str(getal)*i)**2
        extra = aantal-i 
        print(extra*' '+str(uitkomst))
        
#test
getallenboom(7,30)

                             49
                            5929
                           603729
                          60481729
                         6049261729
                        604937061729
                       60493815061729
                      6049382595061729
                     604938270395061729
                    60493827148395061729
                   6049382715928395061729
                  604938271603728395061729
                 60493827160481728395061729
                6049382716049261728395061729
               604938271604937061728395061729
              60493827160493815061728395061729
             6049382716049382595061728395061729
            604938271604938270395061728395061729
           60493827160493827148395061728395061729
          6049382716049382715928395061728395061729
         604938271604938271603728395061728395061729
        60493827160493827160481728395061728395061729
       6049382716049382716049261728395061728395061729
      60493

In [27]:
# De code voor de uitkomst aan het begin van dit notebook

#Kan je ze zo uit printen dat de uitkomst een mooie driehoek wordt?
for i in range(1,10):  
        x = int('1'*i)
        uitkomst = x**2
        extra = (10-i) *' '
        print(extra + str(x) + " x " + str(x) + extra + "=" + extra  + str(uitkomst) )
                   

         1 x 1         =         1
        11 x 11        =        121
       111 x 111       =       12321
      1111 x 1111      =      1234321
     11111 x 11111     =     123454321
    111111 x 111111    =    12345654321
   1111111 x 1111111   =   1234567654321
  11111111 x 11111111  =  123456787654321
 111111111 x 111111111 = 12345678987654321


### Speciale Kerst Boom
* we voegen ook nog een stam toe

In [28]:
def getallenboom_met_stam(getal,aantal,stamdikte):
    for i in range(1,aantal):  
        uitkomst = int(str(getal)*i)**2
        extra = aantal-i 
        lijn = str(extra*' ')+str(uitkomst)
        print(extra*' ',uitkomst)
    # print de stam
    for i in range(5):  
        print( (len(lijn)//2 - (stamdikte//2))*' '+'!'*stamdikte) # let op integer division

# test        
getallenboom_met_stam(1,40,10)

                                        1
                                       121
                                      12321
                                     1234321
                                    123454321
                                   12345654321
                                  1234567654321
                                 123456787654321
                                12345678987654321
                               1234567900987654321
                              123456790120987654321
                             12345679012320987654321
                            1234567901234320987654321
                           123456790123454320987654321
                          12345679012345654320987654321
                         1234567901234567654320987654321
                        123456790123456787654320987654321
                       12345679012345678987654320987654321
                      1234567901234567900987654320987654321
                     1234567901

## Python kan alles! 

### Hierna

* Fibonnaci
* lekker spammen: mails sturen vanuit Python

## Fibonacci

* Zie Wikipedia
    * <https://nl.wikipedia.org/wiki/Rij_van_Fibonacci>
    * <https://en.wikipedia.org/wiki/Fibonacci_number>
    
### Voortplanting van konijnen
<img src='https://artblot.files.wordpress.com/2013/05/fibonacci-rabbits.png'/>

# In formele regels

1. We beginnen met 1 paar konijnen.
2. Elk paar konijnen is na 2 periodes geslachtsrijp
3. Een paar geslachtsrijpe konijnen krijgt altijd 2 kinderen.
4. Konijnen gaat nooit dood.

# Fibonacci reeks in de Nautilus schelp

<img width =40% src='https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/34%2A21-FibonacciBlocks.png/300px-34%2A21-FibonacciBlocks.png'>
<img width =40% src='https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Fibonacci_spiral_34.svg/180px-Fibonacci_spiral_34.svg.png'/>

### Programmeren

1. We maken een functie `fib(n)` waarbij 
    * `n` de generatie is
    * en de _uitkomst_ het aantal paren in die generatie is.

2. Dus 
    * `fib(1)=1`
    * `fib(2)=1`
    * `fib(3)=2`
    * `fib(4)=3`
    * `fib(5)=5`
    * `fib(6)=8`
    * $\ldots$
    

#### In Python

3. De _algemene regel_ is  `fib(n)= fib(n-1)+fib(n-2)`
    * Natuurlijk alleen voor $n\geq 3$.
    * De eerste twee zijn speciale gevallen.

In [29]:
def fib(n): # only correct for input n>=1
    if n==1 or n==2:
        return 1
    else:
        return fib(n-1) + fib(n-2)

In [30]:
# test
for n in range(1,20):
    print(n,fib(n))

1 1
2 1
3 2
4 3
5 5
6 8
7 13
8 21
9 34
10 55
11 89
12 144
13 233
14 377
15 610
16 987
17 1597
18 2584
19 4181


In [34]:
%%time
fib(40)

CPU times: user 30.2 s, sys: 113 ms, total: 30.3 s
Wall time: 30.8 s


102334155

# Nu met echte konijnen

In [35]:
def fib(n):
    if n==1 or n==2:
        return u"\U0001F407" # See https://www.fileformat.info/info/unicode/char/1f407/index.htm
    else:
        return fib(n-1)+fib(n-2)
    
# test
for n in range(1,10):
    print(n,fib(n) )


1 🐇
2 🐇
3 🐇🐇
4 🐇🐇🐇
5 🐇🐇🐇🐇🐇
6 🐇🐇🐇🐇🐇🐇🐇🐇
7 🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇
8 🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇
9 🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇🐇


# Tot slot: mail sturen vanuit Python! 

Is as easy as you like it!
See <https://stackabuse.com/how-to-send-emails-with-gmail-using-python/> where this example below is taken from.
It worked with my gmail account. But I had to allow "insecure apps" to access my Google account.

CAUTION: you can only send 100-150 emails per 24 hours with Gmail SMTP. So don't spam to much ;)

Tip: Make functions to provide and determine the content of your mail.

(Run the actual mail sending code as last)

### Be aware

Google does not accept by default when you mail from with Python. You can tell it to accept it here: <https://myaccount.google.com/lesssecureapps>. Click yes, and the code in the next two cells will run.

First test it by setting `to=['yourown@gmail.com']`

In [41]:
import smtplib

# Zet alle ingredienten


gmail_user = 'yourown@gmail.com'   # Jouw gmail adres
gmail_password = 'yourGooglePassword'           # Jouw wachtwoord yourGooglePassword

sent_from = gmail_user  
to = [ ]  # Lijst met adressen naar wie je gaat sturen
subject = 'OMG Super Important Message'  
body = '''
Hey, what's up?

- You"
'''

email_text = """ 
From: %s  
To: %s  
Subject: %s

%s
""" % (sent_from, ", ".join(to), subject, body)

print(email_text)

 
From: maartenmarx@gmail.com  
To:   
Subject: OMG Super Important Message


Hey, what's up?

- You"




In [43]:
# Stuur de mail nu echt


server = smtplib.SMTP('smtp.gmail.com', 587)
server.ehlo()
server.starttls()
server.login(gmail_user, gmail_password)
server.sendmail(sent_from, to, email_text)
server.close()

# Mail versturen, spammen

* Dit kan natuurlijk nog veel beter
* nettere code
    * geen wachtwoorden in je code!
    * ook de zender als argument van de functie
* Het bericht **personaliseren**.
    * Ipv _"Hallo daar"_ zet je _"Beste ..._"
    * In de brief zet je nog meer persoonlijke dingen
    * **Dat kan allemaal automatisch met Python!**